### ISSUE TITLE
Can you send me the API_MakeDoc script?

### ISSUE THREAD

**Issue by vanasoft23** [NSUSpray/LiveAPI#1]
Title says it all. Hanz Petrov's website contains a broken dropbox link.

Thanks :)

My goal is to write a framework for easy scripting, and have autocomplete in VSCode(and other editors) for ableton live.

thanks,
maxim

**Comment by NSUSpray** [comment]
Hi, maxim! Yes, I have a copy of this archive. You can download it from the link https://github.com/NSUSpray/LiveAPI_MakeDoc
Happy scripting!
